# Generated by Django 2.1.1 on 2019-09-22 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 22, 19, 19, 9, 76326, tzinfo=utc), verbose_name='Fecha publicacion'),
        ),
    ]
